
package de.hpc.soap.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "URISyntaxException", targetNamespace = "http://jaxws.howtodoinjava.com/")
public class URISyntaxException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private URISyntaxException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public URISyntaxException_Exception(String message, URISyntaxException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public URISyntaxException_Exception(String message, URISyntaxException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.hpc.soap.service.URISyntaxException
     */
    public URISyntaxException getFaultInfo() {
        return faultInfo;
    }

}
